### ISSUE TITLE
Failed execution due to package.json "module" error

### ISSUE THREAD

**Issue by goldingdamien** [jsenv/importmap-node-module#58]
While trying to build the import map, I got an error with webidl2.
It was due to module: index.js where index.js does not exist.
How should this be handled?

※ I posted the issue below, but it seems like it would be better to enquire here.
https://github.com/w3c/webidl2.js/issues/721

Regards.

**Comment by dmail** [comment]
Hello, I discover this issue today, I'll check soon and come back to you

**Comment by dmail** [comment]
Hello, sorry for the delay I got sick.

When I'm installing the `webidl2` package from NPM the package.json is correct (there is no "module": "index.js" that would lead to a file that does not exists). This is coherent with what I see on their GitHub repository at https://github.com/w3c/webidl2.js/blob/1d87983912f70f083b61ed5eff20d4c30e40bc00/package.json#L40-L44.

It looks like the faulty package is not theirs. 
Can you post the error message you have?
And can you check what is inside `node_modules/webidl2.js/package.json` in your project on your filesystem?
