### ISSUE TITLE
Why require `name` in the top-level package.json?

### ISSUE THREAD

**Issue by bakkot** [jsenv/importmap-node-module#62]
[This code](https://github.com/jsenv/importmap-node-module/blob/5ff8187a72cc4a0af3483a20985e217e69938910/src/internal/from_package/visitNodeModuleResolution.js#L49-L65) prevents you from running this tool when your top-level `package.json` has an empty `name` field. There's a note saying this shouldn't matter because "npm won't let a package without name be published", but when I'm running against a local directory, my  top-level package.json isn't something which is necessarily going to be published.

Concretely, my workflow for local projects is usually `echo '{}' > package.json; npm i stuff`. That all works fine without a `name` field. I wouldn't add a name unless I was actually going to publish on npm.

**Comment by dmail** [comment]
It looks like the check + warning happens too soon and might be delayed to where package.name is required. At least the root package should be allowed to have no name

**Comment by dmail** [comment]
I'm planning to work on this during the week
