### ISSUE TITLE
Inline import map option

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [jsenv/importmap-node-module#68]
The `npx @jsenv/importmap-node-module project.importmap --entrypoint index.html --remove-unused` command generates the `project.importmap` file. The ReadMe say I need to add the following into the `index.html` code by hand:

```html
<script type="importmap" src="./project.importmap"></script>
```

But I get the `External import maps are not yet supported.` error in the latest version of Chrome.

It seems external import maps are not yet supported in Firefox and Safari too.

What about an option that injects inline import map into the `index.html` code automatically?

```html
<script type="importmap">
  {
    "imports": {},
    "scopes": {}
  }
</script>
```

**Comment by dmail** [comment]
It's funny because was planning to work on that tomorrow:)

**Comment by dmail** [comment]
Would it make sense if the script tries to inline the importmap by default when the file ends with `.html`? (It would either replace the existing importmap script or inject one at the top of the html)

**Comment by FluorescentHallucinogen** [comment]
Here's how it's implemented in JSPM CLI: https://jspm.org/getting-started

```sh
jspm link index.html -p nodemodules -o index.html
```

**Comment by FluorescentHallucinogen** [comment]
> Would it make sense if the script tries to inline the importmap by default when the file ends with `.html`?

Yes.

**Comment by dmail** [comment]
The command will look like this

```console
npx @jsenv/importmap-node-module index.html --entrypoint index.html --remove-unused
```
